// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQIVNJS0rUOQr36RH__dwDwah8OFAXV18',
    appId: '1:660977612451:web:ea6ccc6683f27e1e2cb116',
    messagingSenderId: '660977612451',
    projectId: 'foodie-bc',
    authDomain: 'foodie-bc.firebaseapp.com',
    storageBucket: 'foodie-bc.appspot.com',
    measurementId: 'G-N29K7PX8K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5NL0Bu-FTZsx9EFsmxScZtGqED6NvWU',
    appId: '1:660977612451:android:fd8b8f69fb18525a2cb116',
    messagingSenderId: '660977612451',
    projectId: 'foodie-bc',
    storageBucket: 'foodie-bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSkDCYihtRszJuzQrtjAOn7nb9RsHUaoE',
    appId: '1:660977612451:ios:8ecafeba11d3b33d2cb116',
    messagingSenderId: '660977612451',
    projectId: 'foodie-bc',
    storageBucket: 'foodie-bc.appspot.com',
    iosBundleId: 'com.example.dwitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSkDCYihtRszJuzQrtjAOn7nb9RsHUaoE',
    appId: '1:660977612451:ios:8ecafeba11d3b33d2cb116',
    messagingSenderId: '660977612451',
    projectId: 'foodie-bc',
    storageBucket: 'foodie-bc.appspot.com',
    iosBundleId: 'com.example.dwitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQIVNJS0rUOQr36RH__dwDwah8OFAXV18',
    appId: '1:660977612451:web:a3b21023cd68dcc62cb116',
    messagingSenderId: '660977612451',
    projectId: 'foodie-bc',
    authDomain: 'foodie-bc.firebaseapp.com',
    storageBucket: 'foodie-bc.appspot.com',
    measurementId: 'G-2C7G9FFGL6',
  );
}
